// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package http

import (
	"bank-system-go/internal/config"
	"bank-system-go/internal/delivery/http"
	"bank-system-go/internal/wireset"
)

// Injectors from wire.go:

func Initialize(configPath string) (Application, error) {
	configConfig, err := config.NewConfig(configPath)
	if err != nil {
		return Application{}, err
	}
	logger, err := wireset.InitLogger(configConfig)
	if err != nil {
		return Application{}, err
	}
	httpServer := http.NewHttpServer()
	application := newApplication(logger, configConfig, httpServer)
	return application, nil
}
