app_id: bank-go
release: false

logger:
  level: TRACE
  format: console # json, console

http:
  port: 8080

mq:
  driver: kafka
  kafka_option:
    brokers: 
      - localhost:9092
    consumer_group: "bank"

database:
  driver: postgres
  host: localhost
  port: 5432
  user: root
  password: 123456
  database: local

jwt:
  secret: jfiaom123km
  age: 15m
